site_name: material UI
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
